### ISSUE TITLE
consider adding these

### ISSUE THREAD

**Issue by naorzr** [mikaelbr/awesome-es2015-proxy#29]
Hey @mikaelbr  I've created this article

https://medium.com/@naorzruk/javascript-proxies-russian-roulette-and-some-practical-examples-35f7a1e0612c

and this git repo
[russian roulette](https://github.com/naorzr/rus_roulette)

I'll love it if you could add them up, thanks

**Comment by mikaelbr** [comment]
Thanks! Added now 👍
