### ISSUE TITLE
Add Echo and ComLink to the list

### ISSUE THREAD

**Issue by mrjacobbloom** [mikaelbr/awesome-es2015-proxy#30]
I've been working on a silly little proxy toy called Echo that could be a fun addition to this list: https://github.com/mrjacobbloom/echo -- it prints whatever line of code you write, as long as it starts with `Echo`.

Also, [ComLink](https://github.com/GoogleChromeLabs/comlink) is a very cool library that uses proxies to simplify communication between Web Workers. I definitely think it should be on here

**Comment by mikaelbr** [comment]
Hey! Cool. If you could send a PR (simplest way is just edit through the GH UI) I would be happy to merge.
